version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - copyloopvar
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - misspell
    - nilerr
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    gocritic:
      disabled-checks:
        - ifElseChain
        - singleCaseSwitch
        - commentFormatting
        - exitAfterDefer
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/onflow/atree
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
