# .golangci.yml for github.com/onflow/atree

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - copyloopvar
    - errcheck
    # - forbidigo # TODO: enable forbidigo after adding non-default settings
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nilerr
    - staticcheck
    - typecheck
    - unconvert
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain        # style
      - singleCaseSwitch   # style
      - unslice            # false positives
      - commentFormatting  # does not detect commented out code
      - exitAfterDefer

  goimports:
    local-prefixes: github.com/onflow/atree
