# coverage.yml  Generate and upload Go code coverage report to Codecov.
# https://github.com/onflow/atree/blob/main/.github/workflows/coverage.yml

name: coverage

# Remove permissions from top level and grant in jobs.
permissions: {}

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'release-**'
  pull_request:
    branches:
      - main
      - 'feature/**'
      - 'release-**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          check-latest: true

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build project
        run: go build ./...

      - name: Generate coverage report
        run: go test -timeout 180m -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad # v5.5.3
        with:
            files: ./coverage.txt
            fail_ci_if_error: false # we can set this to true after "Could not find a repository" upload error is fixed
            verbose: true # optional (default = false)
